### ISSUE TITLE
Failed to build MegaBoom

### ISSUE THREAD

**Issue by Ddnirvana** [firesim/firesim#1200]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

1.14.2-0-g8c5416c0

### OS Setup

```
<!-- copy/paste the output of `uname -a; lsb_release -a` below -->
```
Linux ip-192-168-3-79.us-west-2.compute.internal 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

### Other Setup

I tried to build an AFI image of Boom (MegaBoom config). And I just added the following config in the deploy/config_build_recipes.yaml:

```
firesim_dd_megaboom_singlecore_no_nic_l2_llc4mb_ddr3:
    DESIGN: FireSim
    TARGET_CONFIG: DDR3FRFCFSLLC4MB_WithDefaultFireSimBridges_WithFireSimHighPerfConfigTweaks_chipyard.MegaBoomConfig
    PLATFORM_CONFIG: WithAutoILA_F65MHz_BaseF1Config
    deploy_triplet: null
    post_build_hook: null
    metasim_customruntimeconfig: null
    bit_builder_recipe: bit-builder-recipes/f1.yaml
```

And modify the config_build.yaml to only build the ``firesim_dd_megaboom_singlecore_no_nic_l2_llc4mb_ddr3``.

Then I ran a build using:
``firesim buildbitstream``

### Current Behavior

I met the following errors (the full log is attached in the end).
It reports that "the design did not meet timing requirements"

```
2022-09-07 14:50:40,583 [flush       ] [INFO ]  [192.168.2.41] out: INFO: [Common 17-1381] The checkpoint '/home/centos/firesim-build/platforms/f1/aws-fpga/hdk/cl/developer_designs/cl_FireSim-DDR3FRFCFSLLC4MB_WithDefaultFireSimBridges_WithFireSimHighPerfConfigTweaks_chipyard.MegaBoomConfig-WithAutoILA_F65MHz_BaseF1Config/build/checkpoints/to_aws/22_09_07-081044.SH_CL_routed.dcp' has been generated.
2022-09-07 14:50:40,583 [flush       ] [INFO ]  [192.168.2.41] out: write_checkpoint: Time (s): cpu = 00:04:41 ; elapsed = 00:02:55 . Memory (MB): peak = 22239.066 ; gain = 0.000 ; free physical = 169365 ; free virtual = 185913
2022-09-07 14:50:47,953 [flush       ] [INFO ]  [192.168.2.41] out: get_timing_paths: Time (s): cpu = 00:00:54 ; elapsed = 00:00:07 . Memory (MB): peak = 22239.066 ; gain = 0.000 ; free physical = 169374 ; free virtual = 185923
2022-09-07 14:50:48,022 [flush       ] [INFO ]  [192.168.2.41] out:
2022-09-07 14:50:48,023 [flush       ] [INFO ]  [192.168.2.41] out: FATAL: Design did not meet timing requirements. Terminating.
2022-09-07 14:50:52,940 [flush       ] [INFO ]  [192.168.2.41] out: INFO: [Common 17-206] Exiting Vivado at Wed Sep  7 14:50:52 2022...
2022-09-07 14:50:54,352 [flush       ] [INFO ]  [192.168.2.41] out:
2022-09-07 14:50:54,373 [flush       ] [INFO ]  Fatal error: run() received nonzero return code 3 while executing!
2022-09-07 14:50:54,373 [flush       ] [INFO ]  Requested: /home/centos/firesim-build/platforms/f1//aws-fpga/hdk/cl/developer_designs/cl_FireSim-DDR3FRFCFSLLC4MB_WithDefaultFireSimBridges_WithFireSimHighPerfConfigTweaks_chipyard.MegaBoomConfig-WithAutoILA_F65MHz_BaseF1Config/build-bitstream.sh /home/centos/firesim-build/platforms/f1//aws-fpga/hdk/cl/developer_designs/cl_FireSim-DDR3FRFCFSLLC4MB_WithDefaultFireSimBridges_WithFireSimHighPerfConfigTweaks_chipyard.MegaBoomConfig-WithAutoILA_F65MHz_BaseF1Config
2022-09-07 14:50:54,373 [flush       ] [INFO ]  Executed: /bin/bash -l -c "/home/centos/firesim-build/platforms/f1//aws-fpga/hdk/cl/developer_designs/cl_FireSim-DDR3FRFCFSLLC4MB_WithDefaultFireSimBridges_WithFireSimHighPerfConfigTweaks_chipyard.MegaBoomConfig-WithAutoILA_F65MHz_BaseF1Config/build-bitstream.sh /home/centos/firesim-build/platforms/f1//aws-fpga/hdk/cl/developer_designs/cl_FireSim-DDR3FRFCFSLLC4MB_WithDefaultFireSimBridges_WithFireSimHighPerfConfigTweaks_chipyard.MegaBoomConfig-WithAutoILA_F65MHz_BaseF1Config"
2022-09-07 14:50:54,373 [flush       ] [INFO ]  Aborting.
2022-09-07 14:50:54,391 [<module>    ] [ERROR]  Fatal error.
Traceback (most recent call last):
  File "/home/centos/firesim/deploy/firesim", line 508, in <module>
    main(args)
  File "/home/centos/firesim/deploy/firesim", line 448, in main
    t['task'](t['config'](args))
  File "/home/centos/firesim/deploy/firesim", line 293, in buildbitstream
    execute(parallel_build_helper, build_config_file, hosts=build_config_file.build_ip_set)
  File "/opt/conda/envs/firesim/lib/python3.8/site-packages/fabric/tasks.py", line 413, in execute
    error(err)
  File "/opt/conda/envs/firesim/lib/python3.8/site-packages/fabric/utils.py", line 357, in error
    return func(message)
  File "/opt/conda/envs/firesim/lib/python3.8/site-packages/fabric/utils.py", line 65, in abort
    raise e
SystemExit: 1
```

[full log here](https://github.com/firesim/firesim/files/9522890/2022-09-07--07-46-03-buildbitstream-TDODBDDY8OYDXJ0K.log)

### Expected Behavior

Successfully generate the AFI for the MegaBoom

### Other Information

Please see full logs in the above.

**Comment by Ddnirvana** [comment]
Problem solved. close the issue.
