### ISSUE TITLE
Compile error on BankedStore.scala when running buildbitstream

### ISSUE THREAD

**Issue by mbelda** [firesim/firesim#1312]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

1.15.0-0-g93d114de

### OS Setup

```
<!-- copy/paste the output of `uname -a; lsb_release -a` below -->
```
Linux ip-192-168-0-244.ec2.internal 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

### Other Setup

The `buiild-setup.sh` has been executed properly and ended with the Setup complete! message.

### Current Behavior

When I try to execute `firesim buildbitstream` with the default configs for the tutorial the following error appears:
~~~
Executed: /bin/bash -l -c "cd /home/centos/firesim/deploy/../ && export RISCV=/home/centos/firesim/.conda-env/riscv-tools && export PATH=/home/centos/firesim/utils/fireperf:/home/centos/firesim/utils/fireperf/FlameGraph:/home/centos/firesim/sw/firesim-software:/home/centos/firesim/.conda-env/riscv-tools/bin:/opt/Xilinx/Vitis_HLS/2021.2/bin:/opt/Xilinx/Vitis/2021.2/bin:/opt/Xilinx/Vivado/2021.2/bin:/home/centos/firesim/.conda-env/bin:/opt/conda/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/srv/git/centos-git-common:/home/centos/.local/bin:/home/centos/bin:/home/centos/firesim/deploy && export LD_LIBRARY_PATH=/home/centos/firesim/.conda-env/riscv-tools/lib && source sourceme-f1-manager.sh && cd sim/ && make  DESIGN=FireSim TARGET_CONFIG=WithNIC_DDR3FRFCFSLLC4MB_WithDefaultFireSimBridges_WithFireSimHighPerfConfigTweaks_chipyard.LargeBoomConfig PLATFORM_CONFIG=WithAutoILA_F65MHz_BaseF1Config PLATFORM=f1 replace-rtl"
Aborting.
Fatal error.
Traceback (most recent call last):
  File "/home/centos/firesim/deploy/firesim", line 519, in <module>
    main(args)
  File "/home/centos/firesim/deploy/firesim", line 458, in main
    t['task'](t['config'](args))
  File "/home/centos/firesim/deploy/firesim", line 257, in buildbitstream
    execute(build_config.bitbuilder.replace_rtl, hosts=['localhost'])
  File "/home/centos/.local/lib/python3.9/site-packages/fabric/tasks.py", line 385, in execute
    results[host] = _execute(
  File "/home/centos/.local/lib/python3.9/site-packages/fabric/tasks.py", line 277, in _execute
    return task.run(*args, **kwargs)
  File "/home/centos/.local/lib/python3.9/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/centos/firesim/deploy/buildtools/bitbuilder.py", line 120, in replace_rtl
    run(self.build_config.make_recipe("PLATFORM=f1 replace-rtl"))
  File "/home/centos/.local/lib/python3.9/site-packages/fabric/network.py", line 692, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/home/centos/.local/lib/python3.9/site-packages/fabric/operations.py", line 1092, in run
    return _run_command(
  File "/home/centos/.local/lib/python3.9/site-packages/fabric/operations.py", line 959, in _run_command
    error(message=msg, stdout=out, stderr=err)
  File "/home/centos/.local/lib/python3.9/site-packages/fabric/utils.py", line 359, in error
    return func(message)
  File "/home/centos/.local/lib/python3.9/site-packages/fabric/utils.py", line 63, in abort
    raise e
SystemExit: 1
~~~

If I check the log, the first error that ocurs is the following:
~~~2022-11-28 10:20:10,679 [flush       ] [DEBUG]  [localhost] out: [info] compiling 23 Scala sources to /home/centos/firesim/target-design/
chipyard/generators/sifive-cache/target/scala-2.12/classes ...
2022-11-28 10:20:13,485 [flush       ] [DEBUG]  [localhost] out: [error] /home/centos/firesim/target-design/chipyard/generators/sifive-c
ache/design/craft/inclusivecache/src/BankedStore.scala:163:54: constructor cannot be instantiated to expected type;
2022-11-28 10:20:13,485 [flush       ] [DEBUG]  [localhost] out: [error]  found   : (T1, T2)
2022-11-28 10:20:13,485 [flush       ] [DEBUG]  [localhost] out: [error]  required: chisel3.SyncReadMem[Chisel.UInt]
2022-11-28 10:20:13,485 [flush       ] [DEBUG]  [localhost] out: [error]     (which expands to)  chisel3.SyncReadMem[chisel3.UInt]
2022-11-28 10:20:13,486 [flush       ] [DEBUG]  [localhost] out: [error]   val regout = Vec(cc_banks.zipWithIndex.map { case ((b, omSRAM
), i) =>
2022-11-28 10:20:13,486 [flush       ] [DEBUG]  [localhost] out: [error]                                                      ^
2022-11-28 10:20:13,515 [flush       ] [DEBUG]  [localhost] out: [error] /home/centos/firesim/target-design/chipyard/generators/sifive-c
ache/design/craft/inclusivecache/src/BankedStore.scala:190:45: value _1 is not a member of chisel3.SyncReadMem[Chisel.UInt]
2022-11-28 10:20:13,516 [flush       ] [DEBUG]  [localhost] out: [error]   private def banks = cc_banks.map("\"" + _._1.pathName + "\"")
.mkString(",")
~~~

And many more appear after that. I attached the full log.
[2022-11-28--10-19-53-buildbitstream-CPPURWVTDARJOO99.log](https://github.com/firesim/firesim/files/10102717/2022-11-28--10-19-53-buildbitstream-CPPURWVTDARJOO99.log)

### Expected Behavior

I expect the `firesim buildbitstream` command to work properly and generate a design.

**Comment by mbelda** [comment]
I am using FireSim, the last version 0.15.
It does not happen on 0.14 or 0.13.

In fact, I was using 0.13 since last month when it stopped working.
It fails on a call on f1_ami_get_id() or something like that, because aws
cannot find the 1.11.1 version of the AMI anymore.
So I am a bit desperate trying to make the 0.15 work on a new instance.
