### ISSUE TITLE
Can not build and setup on amazon z1d.2xlarge

### ISSUE THREAD

**Issue by Rhythmicc** [firesim/firesim#1792]
### Background Work

- [X] Yes, I searched the [mailing list](https://groups.google.com/forum/#!forum/firesim)
- [X] Yes, I searched [prior issues](https://github.com/firesim/firesim/issues)
- [X] Yes, I searched the [documentation](https://docs.fires.im/en/stable/)

### FireSim Version and Hash

1.20.0-18-g6b4f87e39

### OS Setup

```
<!-- copy/paste the output of `uname -a; lsb_release -a` below -->
```
Linux ip-192-168-5-200.ec2.internal 3.10.0-1160.81.1.el7.x86_64 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.9.2009 (Core)
Release:	7.9.2009
Codename:	Core

### Current Behavior

```
[centos@ip-192-168-5-200 firesim]$ ./build-setup.sh
Channels:
 - conda-forge
 - ucb-bar
Platform: linux-64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/centos/firesim/.conda-lock-env

  added / updated specs:
    - conda-lock=2.5.7


The following NEW packages will be INSTALLED:

...
  
INFO:root:Downloading and Extracting Packages: ...working... done
INFO:root:Preparing transaction: ...working... done
INFO:root:Verifying transaction: ...working... done
INFO:root:Executing transaction: ...working...
INFO:root:
INFO:root:done
INFO:root:#
INFO:root:# To activate this environment, use
INFO:root:#
INFO:root:#     $ conda activate /home/centos/firesim/.conda-env
INFO:root:#
INFO:root:# To deactivate an active environment, use
INFO:root:#
INFO:root:#     $ conda deactivate
INFO:root:
ERROR:root:ERROR: bcrypt-4.2.0-cp39-abi3-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.
ERROR:root:
ERROR:root:ERROR conda.cli.main_run:execute(125): `conda run pip install --no-deps -r /tmp/tmp9ypu44sy` failed. (See above for error)
Traceback (most recent call last):
  File "/home/centos/firesim/.conda-lock-env/bin/conda-lock", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/centos/firesim/.conda-lock-env/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/centos/firesim/.conda-lock-env/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/centos/firesim/.conda-lock-env/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/centos/firesim/.conda-lock-env/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/centos/firesim/.conda-lock-env/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/centos/firesim/.conda-lock-env/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/centos/firesim/.conda-lock-env/lib/python3.12/site-packages/conda_lock/conda_lock.py", line 1498, in click_install
    install(
  File "/home/centos/firesim/.conda-lock-env/lib/python3.12/site-packages/conda_lock/conda_lock.py", line 1552, in install
    install_func(file=lockfile)
  File "/home/centos/firesim/.conda-lock-env/lib/python3.12/site-packages/conda_lock/conda_lock.py", line 240, in do_conda_install
    _conda(["run"], ["pip", "install", "--no-deps", "-r", str(requirements_path)])
  File "/home/centos/firesim/.conda-lock-env/lib/python3.12/site-packages/conda_lock/invoke_conda.py", line 143, in _invoke_conda
    raise subprocess.CalledProcessError(
conda_lock._vendor.poetry.utils._compat.CalledProcessError: Command '['/opt/conda/condabin/conda', 'run', '--prefix', '/home/centos/firesim/.conda-env', 'pip', 'install', '--no-deps', '-r', '/tmp/tmp9ypu44sy']' returned non-zero exit status 1.
```

### Expected Behavior

The error seems to be because the current image uses conda with a python=3.12 environment, but firesim requires version 3.9. I noticed that the python version is restricted in the firesim.yaml file, but after the automatic script runs, the python version in the `/home/centos/firesim/.conda-lock-env` environment is still 3.12.

**Comment by hyuns-lee** [comment]
I have the same issue for firesim v1.17.1, 1.20.1, and HEAD.
Did you resolve it?

**Comment by Rhythmicc** [comment]
> I have the same issue for firesim v1.17.1, 1.20.1, and HEAD. How can you resolve it?

I may avoided this issue by using firesim built into chipyard.  (Because a lot of time has passed, restarting the environment might cost several dollars, so this method may  not be entirely accurate.)

**Comment by hyuns-lee** [comment]
The latest firesim document is updated and according to this,
clone chipyard repo first and setup with it. But it still makes error regarding bcrypt..
