### ISSUE TITLE
stuck at [192.168.4.240] Checking if host instance is up...  while running  firesim infrasetup

### ISSUE THREAD

**Issue by eahmedsalman** [firesim/firesim#296]
I get stuck while running firesim infrasetup
 and i get that error 
```

Building FPGA software driver for FireSimNoNIC-FireSimRocketChipQuadCoreConfig-FireSimDDR3FRFCFSLLC4MBConfig90MHz
[192.168.4.98] Executing task 'instance_liveness'
[192.168.4.98] Checking if host instance is up...


!!! Parallel execution exception under host '192.168.4.98':
Process 192.168.4.98:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python2.7/site-packages/fabric/tasks.py", line 241, in inner
    submit(task.run(*args, **kwargs))
  File "/usr/lib64/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/fabric/decorators.py", line 185, in inner
    return func(*args, **kwargs)
  File "/home/centos/firesim/deploy/runtools/firesim_topology_with_passes.py", line 25, in instance_liveness
    run("uname -a")
  File "/usr/lib64/python2.7/site-packages/fabric/network.py", line 687, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/fabric/operations.py", line 1090, in run
    shell_escape=shell_escape, capture_buffer_size=capture_buffer_size,
  File "/usr/lib64/python2.7/site-packages/fabric/operations.py", line 930, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/usr/lib64/python2.7/site-packages/fabric/state.py", line 435, in default_channel
    chan = _open_session()
  File "/usr/lib64/python2.7/site-packages/fabric/state.py", line 416, in _open_session
    transport = connections[env.host_string].get_transport()
  File "/usr/lib64/python2.7/site-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/usr/lib64/python2.7/site-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/usr/lib64/python2.7/site-packages/fabric/network.py", line 613, in connect
    raise NetworkError(msg, e)
NetworkError: Timed out trying to connect to 192.168.4.98 (tried 10 times)

Fatal error: One or more hosts failed while executing task 'instance_liveness'

Underlying exception:
    Timed out trying to connect to 192.168.4.98 (tried 10 times)

Aborting.
Fatal error.
Traceback (most recent call last):
  File "/home/centos/firesim/deploy/firesim", line 307, in <module>
    main(args)
  File "/home/centos/firesim/deploy/firesim", line 255, in main
    globals()[args.task](simconf)
  File "/home/centos/firesim/deploy/firesim", line 68, in infrasetup
    runtime_conf.infrasetup()
  File "/home/centos/firesim/deploy/runtools/runtime_config.py", line 337, in infrasetup
    self.firesim_topology_with_passes.infrasetup_passes(use_mock_instances_for_testing)
  File "/home/centos/firesim/deploy/runtools/firesim_topology_with_passes.py", line 355, in infrasetup_passes
    execute(instance_liveness, hosts=all_runfarm_ips)
  File "/usr/lib64/python2.7/site-packages/fabric/tasks.py", line 418, in execute
    error(err, exception=d['results'])
  File "/usr/lib64/python2.7/site-packages/fabric/utils.py", line 358, in error
    return func(message)
  File "/usr/lib64/python2.7/site-packages/fabric/utils.py", line 62, in abort
    raise e
SystemExit: 1
The full log of this run is:
/home/centos/firesim/deploy/logs/2019-06-02--14-02-52-infrasetup-JDQL0SXCW6N91G7F.log

```

**Comment by davidbiancolin** [comment]
Closing due to inactivity.
