### ISSUE TITLE
FASED DRAM Model Config Error (on dev branch)

### ISSUE THREAD

**Issue by alonamid** [firesim/firesim#315]
Error when trying to run the FASED DRAM model config script
```
[info] Running firesim.firesim.FireSimRuntimeConfGenerator systolic_dse_ddr sims/firesim/sim/generated-src/f1/FireSim-FireSimRocketChipSystolicConfig-FireSimDDR3FRFCFSLLC4MBConfig_F90MHz firesim.firesim FireSim firesim.firesim FireSimRocketChipSystolicConfig firesim.firesim FireSimDDR3FRFCFSLLC4MBConfig_F90MHz
[error] (run-main-0) java.lang.ClassNotFoundException: firesim.firesim.FireSimRuntimeConfGenerator
[error] java.lang.ClassNotFoundException: firesim.firesim.FireSimRuntimeConfGenerator
[error] 	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[error] 	at sbt.internal.inc.classpath.ClasspathFilter.loadClass(ClassLoaders.scala:70)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[error] 	at java.lang.Class.forName0(Native Method)
[error] 	at java.lang.Class.forName(Class.java:348)
[error] 	at sbt.Run.getMainMethod(Run.scala:103)
[error] 	at sbt.Run.run0(Run.scala:91)
[error] 	at sbt.Run.execute$1(Run.scala:68)
[error] 	at sbt.Run.$anonfun$run$4(Run.scala:80)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
[error] 	at sbt.TrapExit$App.run(TrapExit.scala:253)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Nonzero exit code: 1
[error] (Compile / runMain) Nonzero exit code: 1
[error] Total time: 14 s, completed Jul 16, 2019 1:56:17 AM
make: *** [conf] Error 1
```

**Comment by davidbiancolin** [comment]
@alonamid The easiest workaround for this is to copy the source for the app into Chipyard (drop it in FireChip's Generator.scala)
