### ISSUE TITLE
Fatal error: One or more hosts failed while executing task 'instance_liveness'

### ISSUE THREAD

**Issue by exciting678** [firesim/firesim#449]
I am running the demo at "https://github.com/CSL-KU/firesim-nvdla", and now I just in the "running a single node simulation" step, but when I run the commad "firesim infrasetup", error show as follows:

`FireSim Manager. Docs: http://docs.fires.im
Running: infrasetup

Building FPGA software driver for FireSimNoNIC-FireSimRocketChipQuadCoreConfig-FireSimDDR3FRFCFSLLC4MBConfig90MHz
[192.168.2.71] Executing task 'instance_liveness'
[192.168.2.71] Checking if host instance is up...

Fatal error: One or more hosts failed while executing task 'instance_liveness'

Aborting.
Fatal error.
Traceback (most recent call last):
File "/home/centos/firesim-nvdla/deploy/firesim", line 307, in
main(args)
File "/home/centos/firesim-nvdla/deploy/firesim", line 255, in main
globals()args.task
File "/home/centos/firesim-nvdla/deploy/firesim", line 68, in infrasetup
runtime_conf.infrasetup()
File "/home/centos/firesim-nvdla/deploy/runtools/runtime_config.py", line 337, in infrasetup
self.firesim_topology_with_passes.infrasetup_passes(use_mock_instances_for_testing)
File "/home/centos/firesim-nvdla/deploy/runtools/firesim_topology_with_passes.py", line 355, in infrasetup_passes
execute(instance_liveness, hosts=all_runfarm_ips)
File "/usr/lib64/python2.7/site-packages/fabric/tasks.py", line 420, in execute
error(err)
File "/usr/lib64/python2.7/site-packages/fabric/utils.py", line 358, in error
return func(message)
File "/usr/lib64/python2.7/site-packages/fabric/utils.py", line 62, in abort
raise e
SystemExit: 1
The full log of this run is:
/home/centos/firesim-nvdla/deploy/logs/2019-12-24--14-07-29-infrasetup-27KD2A9BRFKYK83K.log`

How to solve the problem? Thanks!

**Comment by sagark** [comment]
Closing this since it looks like it was resolved here:
https://github.com/CSL-KU/firesim-nvdla/issues/12
