### ISSUE TITLE
firesim launcerunfarm assertion error

### ISSUE THREAD

**Issue by zhushaofeng1992** [firesim/firesim#751]
centos@ip-192-168-1-179.ec2.internal:~/chipyard/sims/firesim$ firesim launchrunfarm
/usr/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.hazmat.backends import default_backend
FireSim Manager. Docs: http://docs.fires.im
Running: launchrunfarm

Fatal error.
Traceback (most recent call last):
  File "/home/centos/chipyard/sims/firesim/deploy/firesim", line 334, in <module>
    main(args)
  File "/home/centos/chipyard/sims/firesim/deploy/firesim", line 280, in main
    simconf = RuntimeConfig(args)
  File "/home/centos/chipyard/sims/firesim/deploy/runtools/runtime_config.py", line 363, in __init__
    self.innerconf.print_cycle_prefix)
  File "/home/centos/chipyard/sims/firesim/deploy/runtools/firesim_topology_with_passes.py", line 67, in __init__
    self.phase_one_passes()
  File "/home/centos/chipyard/sims/firesim/deploy/runtools/firesim_topology_with_passes.py", line 359, in phase_one_passes
    self.pass_perform_host_node_mapping() # TODO: we can know ports here?
  File "/home/centos/chipyard/sims/firesim/deploy/runtools/firesim_topology_with_passes.py", line 252, in pass_perform_host_node_mapping
    self.pass_no_net_host_mapping() 
  File "/home/centos/chipyard/sims/firesim/deploy/runtools/firesim_topology_with_passes.py", line 180, in pass_no_net_host_mapping 
    assert serverind == len(servers), "ERR: all servers were not assigned to a host."
AssertionError: ERR: all servers were not assigned to a host

**Comment by zhushaofeng1992** [comment]
wrong seting the config_runtime.ini
