### ISSUE TITLE
Fatal error: One or more hosts failed while executing task 'instance_liveness'

### ISSUE THREAD

**Issue by srsorry** [firesim/firesim#934]
I get the error when I try the firesim demo by
https://docs.fires.im/en/latest/Running-Simulations-Tutorial/Running-a-Single-Node-Simulation.html
I have try the method by https://github.com/CSL-KU/firesim-nvdla/issues/12, but it doesn't work.
The full error:
/usr/lib/python2.7/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in the next release.
  from cryptography.hazmat.backends import default_backend
FireSim Manager. Docs: http://docs.fires.im
Running: infrasetup

Building FPGA software driver for FireSim-DDR3FRFCFSLLC4MB_WithDefaultFireSimBridges_WithFireSimTestChipConfigTweaks_chipyard.QuadRocketConfig-WithAutoILA_F90MHz_BaseF1Config
[192.168.4.26] Executing task 'instance_liveness'
[192.168.4.26] Checking if host instance is up...

Fatal error: One or more hosts failed while executing task 'instance_liveness'

Aborting.
Fatal error.
Traceback (most recent call last):
  File "/home/centos/firesim/deploy/firesim", line 356, in <module>
    main(args)
  File "/home/centos/firesim/deploy/firesim", line 304, in main
    globals()[args.task](simconf)
  File "/home/centos/firesim/deploy/firesim", line 95, in infrasetup
    runtime_conf.infrasetup()
  File "/home/centos/firesim/deploy/runtools/runtime_config.py", line 380, in infrasetup
    self.firesim_topology_with_passes.infrasetup_passes(use_mock_instances_for_testing)
  File "/home/centos/firesim/deploy/runtools/firesim_topology_with_passes.py", line 399, in infrasetup_passes
    execute(instance_liveness, hosts=all_runfarm_ips)
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 420, in execute
    error(err)
  File "/usr/lib/python2.7/site-packages/fabric/utils.py", line 358, in error
    return func(message)
  File "/usr/lib/python2.7/site-packages/fabric/utils.py", line 62, in abort
    raise e
SystemExit: 1

**Comment by yinlee** [comment]
Hi, may I ask is this problem solved? I encounter the same problem and I can't solve it by using chmod command. Thanks.
