### ISSUE TITLE
No space left on device when running build 

### ISSUE THREAD

**Issue by L-Chocoland** [firesim/firesim#964]
I'm trying to build a Gemmini test on ec2 instance.
I follow the guide to build Gemmini test, When running ./marshal build gemmini-test.json,I get some error below:
DEBUG: Running: "/usr/bin/sudo mount -o loop /home/centos/chipyard/software/firemarshal/images/gemmini-tests.img                                               /home/centos/chipyard/software/firemarshal/disk-mount" in /home/centos/chipyard/software/firemarshal
DEBUG: Running: "/usr/bin/sudo cp -a /home/centos/chipyard/generators/gemmini/software/overlay/root /home/centos                                              /chipyard/software/firemarshal/disk-mount" in /home/centos/chipyard/software/firemarshal
DEBUG: cp: error writing ‘/home/centos/chipyard/software/firemarshal/disk-mount/root/imagenet/resnet50-linux’: N                                          o space left on device
DEBUG: cp: failed to extend ‘/home/centos/chipyard/software/firemarshal/disk-mount/root/imagenet/resnet50-linux’                                              : No space left on device
DEBUG: cp: error writing ‘/home/centos/chipyard/software/firemarshal/disk-mount/root/imagenet/resnet50-baremetal                                              ’: No space left on device
DEBUG: cp: failed to extend ‘/home/centos/chipyard/software/firemarshal/disk-mount/root/imagenet/resnet50-bareme                                              tal’: No space left on device
DEBUG: cp: error writing ‘/home/centos/chipyard/software/firemarshal/disk-mount/root/Makefile’: No space left on                                               device
DEBUG: cp: failed to extend ‘/home/centos/chipyard/software/firemarshal/disk-mount/root/Makefile’: No space left                                               on device
DEBUG: cp: cannot create directory ‘/home/centos/chipyard/software/firemarshal/disk-mount/root/mlps’: No space l                                              eft on device
DEBUG: Running: "/usr/bin/sudo umount /home/centos/chipyard/software/firemarshal/disk-mount" in /home/centos/chi                                              pyard/software/firemarshal
TaskError - taskid:/home/centos/chipyard/software/firemarshal/images/gemmini-tests.img
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/doit/action.py", line 437, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/centos/chipyard/software/firemarshal/wlutil/build.py", line 568, in makeImage
    wlutil.applyOverlay(config['img'], config['overlay'])
  File "/home/centos/chipyard/software/firemarshal/wlutil/wlutil.py", line 655, in applyOverlay
    copyImgFiles(img, flist, 'in')
  File "/home/centos/chipyard/software/firemarshal/wlutil/wlutil.py", line 640, in copyImgFiles
    run(sudoCmd + ['cp', '-a', str(f.src), dst])
  File "/home/centos/chipyard/software/firemarshal/wlutil/wlutil.py", line 511, in run
    raise sp.CalledProcessError(p.returncode, prettyCmd)
subprocess.CalledProcessError: Command '/usr/bin/sudo cp -a /home/centos/chipyard/generators/gemmini/software/ov                                              erlay/root /home/centos/chipyard/software/firemarshal/disk-mount' returned non-zero exit status 1.

ERROR: Failed to build workload gemmini-tests.json
Log available at: /home/centos/chipyard/software/firemarshal/logs/gemmini-tests-build-2022-02-21--09-32-48-EO2Z9                                              QNVXZEAC806.log

It reminds me the space isnt enough,but i set 400GB volume and using df -ih to check space, my space is enough to save the files.so I want to ask if any config is wrong.

**Comment by L-Chocoland** [comment]
my space:
centos@ip-192-168-1-74.ec2.internal:~$ df -ih
Filesystem     Inodes IUsed IFree IUse% Mounted on
devtmpfs         3.8M   354  3.8M    1% /dev
tmpfs            3.8M     1  3.8M    1% /dev/shm
tmpfs            3.8M   462  3.8M    1% /run
tmpfs            3.8M    16  3.8M    1% /sys/fs/cgroup
/dev/nvme0n1p1   200M  747K  200M    1% /
tmpfs            3.8M     1  3.8M    1% /run/user/1000

**Comment by L-Chocoland** [comment]
> I think this is an issue with your FireMarshal root fs not being big enough for the entire workload. Maybe try messing around with https://firemarshal.readthedocs.io/en/latest/workloadConfig.html#rootfs-size

Thank you!
